################################################
---
- name: "configure os at {{ ansible_play_hosts | to_yaml }}"
  hosts: "{{ group_name | default('all') }}"
  gather_facts: no
  any_errors_fatal: true
  become: yes
  vars:
    pl_name: "preconfigure_4_k8s"

################################################
  pre_tasks:
  - block:
    - name: "role check availibility"
      include_role:
        name: r_check_availability

    - name: "role check node os 4 rhel"
      include_role:
        name: r_check_4_rhel

    - name: "role create local facts"
      include_role:
        name: r_create_local_facts

    rescue:
    - fail:
        msg: "pre tasks {{ pl_name }} failed"

    tags:
    - always


################################################
  tasks:
  - block:
    - name: "role configure ntp service"
      include_role:
        name: r_configure_ntp
      tags: 
      - configure_ntp

    - name: "role configure repos"
      include_role:
        name: r_configure_linux_repos.{{ runtime_dist_flag }}
      tags: 
      - configure_linux_repos

    - name: "role update all"
      include_role:
        name: r_update_all.{{ runtime_dist_flag }}
      tags: 
      - update_all

    - name: "role reboot nodes"
      include_role:
        name: r_reboot_nodes
      tags: 
      - reboot_nodes

    - name: "role probe state systemd services"
      include_role:
        name: r_probe_services
      tags: 
      - probe_services

    - name: "role configure sshd service"
      include_role:
        name: r_configure_sshd
      tags: 
      - configure_sshd

    - name: "role configure firewall"
      include_role:
        name: r_configure_firewall.{{ runtime_dist_flag }}
      tags: 
      - configure_firewall

    - name: "role configure selinux"
      include_role:
        name: r_configure_selinux
      tags: 
      - configure_selinux

    - name: "role configure hostsfile"
      include_role:
        name: r_configure_hosts_file
      tags: 
      - configure_hosts_file

    rescue:
    - fail:
        msg: "tasks {{ pl_name }} failed"

################################################
  post_tasks:
  - block:
    - name: "role write local state facts"
      include_role:
        name: r_write_local_state_facts
      tags:
      - always

    rescue:
    - fail:
        msg: "post tasks {{ pl_name }} failed"
