---
# tasks file for r_configure_firewall
  - block:
    - name: "install needed packages"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - firewalld

    - name: "check needed service"
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld

    - name: "configure firewalld"
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
        immediate: yes
      loop: "{{ firewall_port_based.port1.port }}"

    - name: "configure firewalld masqerade"
      firewalld:
        masquerade: "yes"
        permanent: true
        state: enabled
        zone: public

    rescue:
    - fail:
        msg: "configure firewall failed"

    tags:
    - configure_firewall

