---
# vars file for r_configure_firewall

firewall_port_based:
  port1:
    port: 6443,2379,2380,10250,10251,10255,10255
    zone: public

firewall_svc_based:
  svc1:
    service: sshd
    zone: public

